### PR TITLE
Revision: 34608【BUG】【new】【story】【全文索引】集合中的记录无全文索引字段，更新为存在全文索引字段的记录，适配器同步到ES失败

### PR DESCRIPTION
**Pull request by MiroslavGHJ**
【重现步骤】 
1.创建集合并创建全文索引，插入1条不存在全文索引字段的记录 
2.更新该条记录为存在全文索引字段，检查结果 
> db.createCS("test2").createCL("cl",{Group:"group2"}) 
localhost:11810.test2.cl 
Takes 0.298815s. 
> db.test2.cl.createIndex("a",{a:"text"}) 
Takes 0.183272s. 
> db.test2.cl.insert({a:"aaaa"}) 
Takes 0.012989s. 
> db.test2.cl.insert({b:"bbbb"}) 
Takes 0.001499s. 
> db.test2.cl.update({$set:{a:"update"}},{b:"bbbb"}) 
Takes 0.001883s. 
【预期结果】 
1.数据正常同步到ES 
【实际结果】 
1.数据同步到ES失败，在ES端无法查询到更新的记录，此时固定集合中存在该条记录，且值正确；如下： 
> data2.SYS_4241699143.SYS_4241699143.find() 
{ 
  "_id": 0, 
  "Type": 1, 
  "_rid": "5a976fda3f88581a20000000", 
  "_source": { 
    "a": "aaaa" 
  } 
} 
{ 
  "_id": 120, 
  "Type": 3, 
  "_rid": "5a976fe73f88581a20000001", 
  "_source": { 
    "a": "update" 
  } 
} 
Return 2 row(s). 
检查适配器端存在错误日志： 
 Level:DEBUG 
PID:13049 TID:11670 
Function:_parseSrcData Line:733 
File:SequoiaDB/engine/tools/seadapter/seAdptIndexSession.cpp 
Message: 
Operation type: 3, _lid: 120, _id: 5a976fe73f88581a20000001, _source: { "a": "update" } 
 Level:DEBUG 
PID:13049 TID:11670 
Function:_bulkFinish Line:1430 
File:SequoiaDB/engine/tools/seadapter/seAdptIndexSession.cpp 
Message: 
Bulk operation data: {"update":{"_id":"5a976fe73f88581a20000001"}} 
{"doc":{ "a": "update" }} 

Level:DEBUG 
PID:13049 TID:11670 
Function:_sendMessage Line:549 
File:SequoiaDB/engine/tools/seadapter/utilHttp.cpp 
Message: 
Request string is: POST /sys_4241699143_group2/group2/_bulk HTTP/1.1^M 
Host: 192.168.31.64^M 
Accept: application/json^M 
Connection: Keep-Alive^M 
Content-Type: application/json^M 
Content-length: 72^M 
^M 
{"update":{"_id":"5a976fe73f88581a20000001"}} 
{"doc":{ "a": "update" }} 

 Level:ERROR 
PID:13049 TID:11670 
Function:bulk Line:711 
File:SequoiaDB/engine/tools/seadapter/utilESClt.cpp 
Message: 
Operation on remote failed. Reply: {"took":2,"errors":true,"items":[{"update":{"_index":"sys_4241699143_group2","_type":"group2","_id":"5a976fe73f88581a20000001","status":404,"error":{"type":"document_missing_exception","reason":"[group2][5a976fe73f88581a20000001]: document missing","index_uuid":"b7AGImfmRMmg2lFd3oKO2A","shard":"0","index":"sys_4241699143_group2"}}}]}0 

 Level:ERROR 
PID:13049 TID:11670 
Function:_bulkFinish Line:1433 
File:SequoiaDB/engine/tools/seadapter/seAdptIndexSession.cpp 
Message: 
Bulk operation failed[ 0 ] 

Level:ERROR 
PID:13049 TID:11670 
Function:_processCappedCLRecords Line:1018 
File:SequoiaDB/engine/tools/seadapter/seAdptIndexSession.cpp 
Message: 
Finish operation of bulk failed[ -10 ] 

Level:ERROR 
PID:13049 TID:11670 
Function:handleGetMoreRes Line:294 
File:SequoiaDB/engine/tools/seadapter/seAdptIndexSession.cpp 
Message: 
Process data of capped collection failed[ -10 ] 

Level:DEBUG 
PID:13049 TID:11670 
Function:dispatchMsg Line:226 
File:SequoiaDB/engine/include/pmdObjBase.hpp 
Message: 
[_seAdptIndexSession]Process func[handleGetMoreRes] failed[rc = -10] 

Level:DEBUG 
PID:13049 TID:13051 
Function:_sendIdxUpdateReq Line:1411 
File:SequoiaDB/engine/tools/seadapter/seAdptMgr.cpp 
Message: 
Send text index update request to data node. Message: { "Version": 8 } 

 Level:DEBUG 
PID:13049 TID:13052 
Function:_readCallback Line:632 
File:SequoiaDB/engine/net/netEventHandler.cpp 
Message: 
Connection[Handle:5, Node:{ GroupID:10000, NodeID:10000, ServiceID:2(SHARD) }] recieved message[Length: 82, OpCode: (1)10001,TID: 0, RouteID: { GroupID:1001, NodeID:1038, ServiceID:2(SHARD) },RequestID: 0] from 127.0.0.1:11842 

【备注】 
更新全文索引字段为无报错 
> db.test.test.update({$unset:{a:"",b:""}}) 
Takes 0.397516s. 
> db.test.test.findOne() 
{ 
  "_id": { 
    "$oid": "5a98ef3966f69e953a001770" 
  }, 
  "c": "aundefinedvmptundefinedundefinedundefineddundefinedundefinedtlkhtibdundefinedundefinednuundefinedevundefinedundefinedpundefinedu" 
} 
Return 1 row(s). 

log: 
 Level:DEBUG 
PID:15028 TID:15530 
Function:_sendMessage Line:549 
File:SequoiaDB/engine/tools/seadapter/utilHttp.cpp 
Message: 
{"doc":{ "": {"$undefined":1}, "": {"$undefined":1} }} 
{"update":{"_id":"5a98ef3b66f69e953a0020e1"}} 
Level:ERROR 
PID:15028 TID:15530 
Function:_processReply Line:177 
File:SequoiaDB/engine/tools/seadapter/utilESClt.hpp 
Message: 
Request processed failed[ -10 ], respond message: {"error":{"root_cause":[{"type":"json_parse_exception","reason":"Duplicate field ''\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1ea16bf1; line: 1, column: 34]"}],"type":"json_parse_exception","reason":"Duplicate field ''\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1ea16bf1; line: 1, column: 34]"},"status":500} 

测试用例： 
seqDB-12027 :: 版本: 1 :: 使用update接口更新全文索引字段 
seqDB-12029 :: 版本: 1 :: 更新记录，使记录中的索引字段存在/不存在

### CODE REVIEW

**Comment by MieczyslawBBM** [comment]
请安排分析

**Comment by BranimirCVB** [comment]
请安排测试

**Comment by MieczyslawBBM** [comment]
请验证

**Comment by StanislawUIO** [comment]
请验证

**Comment by MiroslavGHJ** [comment]
【验证结果】：验证问题已经解决，请检视 

【回归版本】 
SequoiaDB shell version: 2.9 

【验证步骤】 
执行回归备注一步骤正确无问题，执行回归补充备注步骤正确无问题 
1.创建集合创建索引  
db.createCS("test2").createCL("cl",{Group:"group2"})  
db.test2.cl.createIndex("a",{a:"text",b:"text"})  
2.插入记录  
db.test2.cl.insert({a:"ceshi3",b:"ceshi3",c:"changshi"})  
3.删除其中一个索引字段  
db.test2.cl.update({$unset:{a:""}},{c:"changshi"})  
4.es查询索引a字段已删除 
5.删除剩余索引字段，删除成功，es查询无该记录 
db.test2.cl.update({$unset:{b:""}},{c:"changshi"}) 
【测试用例】 
seqDB-12027 :: 版本: 1 :: 使用update接口更新全文索引字段   
seqDB-12029 :: 版本: 1 :: 更新记录，使记录中的索引字段存在/不存在

**Comment by StanislawUIO** [comment]
检视通过，请关闭

**Pull request merged**
