### PR TITLE
【story】开发支持SequoiaSQL的OM插件

### PR DESCRIPTION
**Pull request by MiroslavGHJ**
【Story描述】 
开发支持SequoiaSQL的OM插件 

相关命令： 
1. ssql exec 执行sql查询 

注意：最新版文档，请参考 /trunk/internal_doc/03.开发设计/OM/插件文档/Story_om svc的SequoiaSQL插件.doc

### CODE REVIEW

**Comment by MieczyslawBBM** [comment]
请开发

**Comment by BranimirCVB** [comment]
SequoiaSQL的om svc插件 
---- 
Added : /trunk/tools/om_plugins/sql_oltp/pom.xml 
Added : /trunk/tools/om_plugins/sql_oltp/src 
Added : /trunk/tools/om_plugins/sql_oltp/src/main 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/Crypto.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/HttpController.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/Register.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/Runner.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/SsqlOltpPlugin.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/config 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/config/OmsvcConfig.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/config/PluginConfig.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/dao 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/dao/DbOperations.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/java/com/sequoiadb/plugin/dao/SqlOperations.java 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/resources 
Added : /trunk/tools/om_plugins/sql_oltp/src/main/resources/application.properties 
Added : /trunk/tools/om_plugins/sql_oltp/src/test 
Added : /trunk/tools/om_plugins/sql_oltp/src/test/java 
Added : /trunk/tools/om_plugins/sql_oltp/ssqloltp-plugin.iml

**Comment by BranimirCVB** [comment]
重新调整ssql-oltp插件的目录结构 
---- 
Added : /trunk/tools/om_plugins/sql_oltp/bin 
Added : /trunk/tools/om_plugins/sql_oltp/config 
Deleted : /trunk/tools/om_plugins/sql_oltp/pom.xml 
Added : /trunk/tools/om_plugins/sql_oltp/source 
Added : /trunk/tools/om_plugins/sql_oltp/source/pom.xml 
Added : /trunk/tools/om_plugins/sql_oltp/source/src 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/Crypto.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/HttpController.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/Register.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/Runner.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/SsqlOltpPlugin.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/config 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/config/OmsvcConfig.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/config/PluginConfig.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/dao 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/dao/DbOperations.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/java/com/sequoiadb/plugin/dao/SqlOperations.java 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/resources 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/main/resources/application.properties 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/test 
Added : /trunk/tools/om_plugins/sql_oltp/source/src/test/java 
Added : /trunk/tools/om_plugins/sql_oltp/source/ssqloltp-plugin.iml 
Deleted : /trunk/tools/om_plugins/sql_oltp/src 
Deleted : /trunk/tools/om_plugins/sql_oltp/ssqloltp-plugin.iml 
Added : /trunk/tools/om_plugins/sql_oltp/www

**Comment by BranimirCVB** [comment]
【CheckList】 
检查项---------------------------------------------------------结论（NA/N/Y） 
-------------------------------------------------------------------------------------------- 
修改代码是否全部提交SVN主干和分支版本 
且符合代码规范--------------------------------------------y 主干 
是否用例全部通过-----------------------------------------y 手工测试 
修改代码是否通过检视------------------------------------y 
资料是否变更-----------------------------------------------n 
接口是否变更-----------------------------------------------n 
相关驱动是否变更或添加---------------------------------na 
是否保持向前兼容------------------------------------------y 
是否影响安装部署和监控---------------------------------n 
是否影响性能-----------------------------------------------n 
sdb shell帮助信息是否更新------------------------------na

**Comment by BranimirCVB** [comment]
请开发网页

**Comment by MiroslavGHJ** [comment]
SAC 网页部分 

【提交记录】 

Message: 
SEQUOIADBMAINSTREAM-3115 sac 
1.新增OLTP数据库、数据操作、表结构操作页面。 
2.部署首页“设置鉴权”当业务类型为OLTP时，可以设置默认数据库。 
---- 
Modified : /trunk/SequoiaDB/web/app/controller/Deploy/Index.js 
Modified : /trunk/SequoiaDB/web/app/controller/Public.js 
Modified : /trunk/SequoiaDB/web/app/directive/directive.js 
Modified : /trunk/SequoiaDB/web/app/other/lib/function.js 
Modified : /trunk/SequoiaDB/web/app/template/Component/Form.html 
Modified : /trunk/SequoiaDB/web/app/template/Deploy/Index.html 
Added : /trunk/tools/om_plugins/sql_oltp/www/app 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/config 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/config/Route.json 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Database 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Database/Index.js 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Operate 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Operate/Data.js 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Operate/Structure.js 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/language 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/language/English.json 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Database 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Database/Index.html 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Operate 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Operate/Data.html 
Added : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Operate/Structure.html 


Message: 
SEQUOIADBMAINSTREAM-3115 sac 
1.修复OLTP数据库页面重命名table完成之后查询table列表的错误问题。 
---- 
Modified : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Database/Index.js 

Message: 
SEQUOIADBMAINSTREAM-3115 sac 
1.修复oltp数据操作页面删除操作的错误。 
2.调整oltp数据操作页面查询操作、更新操作。 
---- 
Modified : /trunk/tools/om_plugins/sql_oltp/www/app/controller/Data/OLTP/Operate/Data.js 
Modified : /trunk/tools/om_plugins/sql_oltp/www/app/template/Data/OLTP/Operate/Data.html 

【CheckList】 
检查项---------------------------------------------------------结论（NA/N/Y） 
-------------------------------------------------------------------------------------------- 
修改代码是否全部提交SVN主干和分支版本 
且符合代码规范--------------------------------------------Y 主干 
是否用例全部通过-----------------------------------------NA 手工测试 
修改代码是否通过检视------------------------------------y 页面检视 
资料是否变更-----------------------------------------------n 
接口是否变更-----------------------------------------------n 
相关驱动是否变更或添加---------------------------------n 
是否保持向前兼容------------------------------------------y 
是否影响安装部署和监控---------------------------------n 
是否影响性能-----------------------------------------------n 
sdb shell帮助信息是否更新------------------------------na

**Comment by MieczyslawBBM** [comment]
请安排测试

**Comment by StanislawUIO** [comment]
【验证结果】：story已验证完成，请关闭该story单 

【回归版本】 
SequoiaDB shell version: 3.0.0 

【测试用例】 
seqDB-15091 :: 版本: 1 :: 启动om连接器插件  
seqDB-15092 :: 版本: 1 :: 停止om连接器插件  
seqDB-15093 :: 版本: 1 :: 查看om连接器插件状态  
...... 
seqDB-15119 :: 版本: 1 :: 内存不足 
【问题单】 
SEQUOIADBMAINSTREAM-3458 
【bug】【new】【story】【OM】关联业务选择多个coord节点时，只使用一个协调节点 
SEQUOIADBMAINSTREAM-3453 
【bug】【new】【story】【OM-SequoiaSQL插件】外表创建时不存在集合，查询失败后再创建集合后查询还是失败 
SEQUOIADBMAINSTREAM-3452 
【bug】【new】【story】【OM-SequoiaSQL插件】创建表时，设置字段主键或者唯一时创建失败 
SEQUOIADBMAINSTREAM-3451 
【bug】【new】【story】【OM-SequoiaSQL插件】修改表名使用下划线开头修改失败 
SEQUOIADBMAINSTREAM-3449 
【bug】【new】【story】【OM-SequoiaSQL插件】优化单 
SEQUOIADBMAINSTREAM-3448 
【bug】【new】【story】【OM】未取消关联时删除关联的数据库，取消关联失败 
【测试报告】 
E:\trunk\internal_doc\06.测试报告\story测试报告\story-om增加插件框架测试报告.doc

**Pull request merged**
